Repository dogfoot-birdfoot/footprint-front, pull requests merged in 2024-03, with the labels that each got.

#1 [DBFP-2]Feature : layout 구성 , mainpage까지 구성된 상태
  package-lock.json
  package.json
  public/mainImage.jpg
  src/App.tsx
  src/components/card/CardItem.tsx
  src/components/card/styles/CardItemStyle.ts
  src/components/layout/Footer.tsx
  src/components/layout/Layout.tsx
  src/components/layout/NavBar.tsx
  src/components/layout/styles/FooterStyle.ts
  src/components/layout/styles/LayoutStyle.ts
  src/components/layout/styles/NavBarStyle.ts
  src/components/temp.tsx
  src/index.css
  src/pages/LoginPage/LoginPage.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/MainPage/Reviews.tsx
  src/pages/MainPage/styles/MainPageStyle.ts
  src/pages/MainPage/styles/ReviewStyle.ts
Labels: :sparkles: FEATURE

#2 [DBFP-4]feat: 리뷰갤러리 호버시 상세정보 표기 및 태그위치 고정
  src/pages/MainPage/Reviews.tsx
  src/pages/MainPage/styles/ReviewStyle.ts
Labels: :sparkles: FEATURE

#3 [FP-4]Feature: login, register form 구성
  package-lock.json
  package.json
  src/App.tsx
  src/components/Footer.tsx
  src/components/NavBar.tsx
  src/components/card/CardItem.tsx
  src/components/layout/Layout.tsx
  src/components/styles/FooterStyle.ts
  src/components/styles/LayoutStyle.ts
  src/components/styles/NavBarStyle.ts
  src/pages/LoginPage/LoginPage.tsx
  src/pages/LoginPage/SignInForm.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/MainPage/ReviewsGallery.tsx
  src/pages/RegisterPage/RegisterForm.tsx
  src/pages/RegisterPage/RegisterPage.tsx
  src/styles/LoginPageStyle.ts
  src/styles/MainPageStyle.ts
  src/styles/ReviewGalleryStyle.ts
Labels: :sparkles: FEATURE

#4 [FP-12]Feature: 벨 버튼 클릭시 알림창 드롭다운
  src/components/NavBar.tsx
Labels: :sparkles: FEATURE

#5 [FP-16]Feature: 전체일정공유페이지
  src/App.tsx
  src/components/NavBar.tsx
  src/pages/ScheduleSharePage/ScheduleSharePage.tsx
  src/styles/MainPageStyle.ts
  src/styles/PlanSharePageStyle.ts
Labels: :sparkles: FEATURE

#6 style: 스타일 위치 변경 및 전역 변수 추가
  src/App.tsx
  src/components/NavBar.tsx
  src/components/styles/NavBarStyle.ts
  src/pages/LoginPage/LoginPage.tsx
  src/pages/LoginPage/LoginPageStyle.ts
  src/pages/LoginPage/SignInForm.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/MainPage/MainPageStyle.ts
  src/pages/RegisterPage/RegisterForm.tsx
  src/pages/RegisterPage/RegisterPage.tsx
  src/pages/ScheduleSharePage/PlanSharePageStyle.ts
  src/pages/ScheduleSharePage/ScheduleSharePage.tsx
  src/styles/theme.ts
Labels: :art: STYLE, :recycle: REFACTOR

#8 [FP-5, FP-6] feature: 마이페이지 UI, 내 프로필 페이지 추가
  src/App.tsx
  src/components/NavBar.tsx
  src/components/layout/Layout.tsx
  src/components/layout/LayoutStyle.ts
  src/components/sidebar/SideBar.tsx
  src/components/sidebar/SideBarStyle.ts
  src/components/switch/PubPrivSwitch.tsx
  src/components/switch/SwitchTheme.tsx
  src/components/switch/type.d.ts
  src/pages/MainPage/ReviewGalleryStyle.ts
  src/pages/MainPage/ReviewsGallery.tsx
  src/pages/MyFavoritePage/MyFavorite.tsx
  src/pages/MyFavoritePage/MyFavoriteStyle.ts
  src/pages/MySchedulePage/MySchedule.tsx
  src/pages/MySchedulePage/MyScheduleStyle.ts
  src/pages/ProfilePage/MyProfile.tsx
  src/pages/ProfilePage/MyProfileStyle.ts
  src/styles/styles.ts
  src/styles/theme.ts
Labels: :lipstick: DESIGN, :sparkles: FEATURE

#9 [FP-19]Feature: schdule detail page
  src/App.tsx
  src/components/Buttons/Buttons.tsx
  src/components/DaySummary/DaySummary.style.ts
  src/components/DaySummary/DaySummary.tsx
  src/components/DayTab/DayTab.tsx
  src/components/Footer.tsx
  src/components/HorizontalCard/HorizontalCard.style.ts
  src/components/HorizontalCard/HorizontalCard.tsx
  src/components/KakaoButton/KakaoButton.style.ts
  src/components/KakaoButton/KakaoButton.tsx
  src/components/Map/Map.tsx
  src/components/NavBar.tsx
  src/components/Tag/Tag.style.ts
  src/components/Tag/Tag.tsx
  src/components/card/CardItem.tsx
  src/components/card/styles/CardItem.style.ts
  src/components/layout/Layout.tsx
  src/pages/LoginPage/LoginPage.style.ts
  src/pages/LoginPage/LoginPage.tsx
  src/pages/LoginPage/SignInForm.tsx
  src/pages/MainPage/MainPage.style.ts
  src/pages/MainPage/MainPage.tsx
  src/pages/MainPage/ReviewGallery.style.ts
  src/pages/MainPage/ReviewsGallery.tsx
  src/pages/RegisterPage/RegisterForm.tsx
  src/pages/RegisterPage/RegisterPage.tsx
  src/pages/ScheduleDetailPage/ScheduleDetailPage.style.ts
  src/pages/ScheduleDetailPage/ScheduleDetailPage.tsx
  src/pages/ScheduleSharePage/ScheduleSharePage.style.ts
  src/pages/ScheduleSharePage/ScheduleSharePage.tsx
Labels: :lipstick: DESIGN, :sparkles: FEATURE

#10 [FP-9] feature: 내 즐겨찾기 페이지 추가
  src/components/sidebar/SideBarStyle.ts
  src/pages/MyFavoritePage/MyFavorite.tsx
  src/pages/MyFavoritePage/MyFavoriteStyle.ts
  src/pages/ProfilePage/MyProfileStyle.ts
  src/styles/styles.ts
Labels: :sparkles: FEATURE, :art: STYLE

#11 [FP-7] feature: 내 여행일정 페이지 추가
  src/components/DaySummary/DaySummary.style.ts
  src/components/DaySummary/DaySummary.tsx
  src/components/HorizontalCard/HorizontalCard.tsx
  src/components/switch/PubPrivSwitch.tsx
  src/components/switch/type.d.ts
  src/pages/MyFavoritePage/MyFavorite.style.ts
  src/pages/MyFavoritePage/MyFavorite.tsx
  src/pages/MySchedulePage/DetailSchedule.style.ts
  src/pages/MySchedulePage/DetailSchedule.tsx
  src/pages/MySchedulePage/MySchedule.style.ts
  src/pages/MySchedulePage/MySchedule.tsx
  src/pages/ScheduleDetailPage/ScheduleDetailPage.tsx
Labels: :sparkles: FEATURE, :recycle: REFACTOR

#12 [FP-60]style: 전체 여백조정
  src/pages/MainPage/MainPage.style.ts
  src/pages/MainPage/MainPage.tsx
  src/pages/MainPage/ReviewGallery.style.ts
  src/pages/ScheduleDetailPage/ScheduleDetailPage.tsx
  src/pages/ScheduleSharePage/ScheduleSharePage.style.ts
Labels: :art: STYLE

#13 [FP-35]Feature:review 모아보기 페이지, review 상세페이지
  src/App.tsx
  src/components/DaySummary/DaySummary.tsx
  src/components/HorizontalCard/HorizontalCard.tsx
  src/components/KakaoButton/KakaoButton.style.ts
  src/components/KakaoButton/KakaoButton.tsx
  src/components/NavBar/NavBar.tsx
  src/components/card/CardItem.tsx
  src/pages/ReviewDetailPage/ReviewDetailPage.tsx
  src/pages/ReviewSharePage/ReviewSharePage.tsx
  src/pages/ScheduleDetailPage/ScheduleDetailPage.style.ts
  src/pages/ScheduleDetailPage/ScheduleDetailPage.tsx
Labels: :sparkles: FEATURE, :art: STYLE

#14 [FP-35]Feature: 리뷰 상세페이지 이미지 슬라이더 추가
  src/components/HorizontalCard/HorizontalCard.style.ts
  src/pages/MainPage/ReviewGallery.style.ts
  src/pages/ReviewDetailPage/ImageSlider.style.ts
  src/pages/ReviewDetailPage/ImageSlider.tsx
  src/pages/ReviewDetailPage/ReviewDetailPage.tsx
  src/pages/ScheduleDetailPage/ScheduleDetailPage.style.ts
Labels: :sparkles: FEATURE, :art: STYLE

#15 [FP-7] design: DaySummary CSS 변경 및 내 여행일정 페이지 디자인 수정
  src/components/DaySummary/DaySummary.style.ts
  src/components/DaySummary/DaySummary.tsx
  src/components/DayTab/DayTab.tsx
  src/components/HorizontalCard/HorizontalCard.style.ts
  src/components/HorizontalCard/HorizontalCard.tsx
  src/components/HorizontalCard/type.d.ts
  src/components/KakaoButton/KakaoButton.style.ts
  src/pages/MySchedulePage/DetailSchedule.style.ts
  src/pages/MySchedulePage/DetailSchedule.tsx
  src/pages/MySchedulePage/MySchedule.style.ts
  src/pages/ProfilePage/MyProfile.style.ts
Labels: :lipstick: DESIGN

#16 [FP-28]Feature: 검색페이지 구현 (리뷰와 일정에대해 각각 표시)
  public/footprintlogo.png
  src/App.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/SearchBar.style.ts
  src/components/NavBar/SearchBar.tsx
  src/components/card/CardItem.tsx
  src/pages/ReviewDetailPage/ReviewDetailPage.tsx
  src/pages/SearchResultPage/SearchResultPage.tsx
Labels: :sparkles: FEATURE, :art: STYLE

#17 style: 배지가 동적으로 표시되도록 수정
  src/components/card/CardItem.tsx
Labels: :art: STYLE

#18 [FP-30] Feature: add Schedule page
  package-lock.json
  package.json
  src/App.tsx
  src/components/NavBar/NavBar.tsx
  src/pages/CreateSchedulePage/AddDestination.style.ts
  src/pages/CreateSchedulePage/AddDestination.tsx
  src/pages/CreateSchedulePage/AddPost.tsx
  src/pages/CreateSchedulePage/AddSchedule.tsx
  src/pages/CreateSchedulePage/Calendar.style.ts
  src/pages/CreateSchedulePage/Calendar.tsx
  src/pages/CreateSchedulePage/CreateScheduleForm.tsx
  src/pages/CreateSchedulePage/CreateSchedulePage.tsx
  src/pages/CreateSchedulePage/SearchBox.tsx
Labels: :sparkles: FEATURE, :art: STYLE

#19 [FP-21, FP-24, FP-34] feature: 리뷰 추가 페이지
  src/App.tsx
  src/components/DropDownButton/DropDownButton.style.ts
  src/components/DropDownButton/DropDownButton.tsx
  src/components/DropDownButton/type.d.ts
  src/components/ImageSlider/ImageSlider.style.ts
  src/components/ImageSlider/ImageSlider.tsx
  src/components/ImageSlider/type.d.ts
  src/components/NavBar/NavBar.style.ts
  src/components/NavBar/NavBar.tsx
  src/components/layout/Layout.style.ts
  src/components/sidebar/SideBar.tsx
  src/components/switch/OnOffSwitch.tsx
  src/components/switch/SwitchTheme.tsx
  src/components/switch/type.d.ts
  src/index.css
  src/pages/AddReviewPage/AddIntro.style.ts
  src/pages/AddReviewPage/AddIntro.tsx
  src/pages/AddReviewPage/AddPictures.style.ts
  src/pages/AddReviewPage/AddPictures.tsx
  src/pages/AddReviewPage/AddPost.style.ts
  src/pages/AddReviewPage/AddPost.tsx
  src/pages/AddReviewPage/AddReviewPage.style.ts
  src/pages/AddReviewPage/AddReviewPage.tsx
  src/pages/AddReviewPage/type.d.ts
  src/pages/MyFavoritePage/MyFavorite.tsx
  src/pages/MySchedulePage/MySchedule.tsx
  src/pages/ProfilePage/MyProfile.tsx
  src/pages/ReviewDetailPage/ReviewDetailPage.tsx
  src/styles/theme.ts
Labels: :lipstick: DESIGN, :sparkles: FEATURE, :art: STYLE

#20 Feature/create schedule page
  package-lock.json
  package.json
  src/App.tsx
  src/components/NavBar/NavBar.tsx
  src/components/sidebar/SideBar.tsx
  src/pages/AddReviewPage/AddReviewPage.tsx
  src/pages/CreateSchedulePage/AddSchedule.tsx
  src/pages/CreateSchedulePage/CreateSchedulePage.tsx
  src/pages/CreateSchedulePage/SearchBox.tsx
  src/pages/CreateSchedulePage/selectedPlaceState.ts
  src/pages/MyFavoritePage/MyFavorite.tsx
  src/pages/ReviewDetailPage/ReviewDetailPage.tsx
Labels: :sparkles: FEATURE, :art: STYLE

#22 [FP-15]Feature: Add Post 폼 구현, 스케줄 추가시 메모와 경비 시간선택 구현
  package-lock.json
  package.json
  src/components/Map/Map.tsx
  src/components/Tag/Tag.style.ts
  src/components/Tag/Tag.tsx
  src/pages/CreateSchedulePage/AddPost.tsx
  src/pages/CreateSchedulePage/AddSchedule.tsx
  src/pages/CreateSchedulePage/CreateScheduleForm.tsx
  src/pages/CreateSchedulePage/type.d.ts
  src/pages/ScheduleDetailPage/ScheduleDetailPage.style.ts
  src/pages/ScheduleDetailPage/ScheduleDetailPage.tsx
Labels: :lipstick: DESIGN, :sparkles: FEATURE

#23 [FP-13, FP-14] feature: 일정 불러오기 modal 및 기능 추가
  src/components/DaySummary/DaySummary.style.ts
  src/components/DaySummary/DaySummary.tsx
  src/components/HorizontalCard/HorizontalCard.tsx
  src/components/HorizontalCard/type.d.ts
  src/pages/CreateSchedulePage/AddSchedule.tsx
  src/pages/CreateSchedulePage/CreateScheduleForm.tsx
  src/pages/CreateSchedulePage/LoadSchedule.style.ts
  src/pages/CreateSchedulePage/LoadSchedule.tsx
  src/pages/CreateSchedulePage/SearchBox.tsx
  src/pages/CreateSchedulePage/type.d.ts
Labels: :lipstick: DESIGN, :sparkles: FEATURE, :recycle: REFACTOR

#24 [FP-65]style: 좋아요와 즐겨찾기 버튼 추가
  package-lock.json
  package.json
  src/components/KakaoButton/KakaoButton.style.ts
  src/components/NavBar/NavBar.tsx
  src/firebase.ts
  src/hooks/loginAtom.ts
  src/hooks/selectedPlaceState.ts
  src/pages/LoginPage/LoginPage.style.ts
  src/pages/LoginPage/SignInForm.tsx
  src/pages/RegisterPage/RegisterForm.tsx
Labels: :sparkles: FEATURE, :art: STYLE

#25 [FP-69]feat: mirage js 초기 설정 및 세팅
  package-lock.json
  package.json
  src/App.tsx
  src/components/NavBar/NavBar.tsx
  src/mirage/index.ts
  src/mirage/models/user.ts
  src/mirage/routes/userRoutes.ts
  src/mirage/serializer/user.ts
  src/pages/MirageExample.tsx
Labels: :sparkles: FEATURE

#26 [FP-70, FP-71] refactor: 레이아웃 최소 min-height를 지정해 스크롤바 생성, MyPage 구조 리팩토링
  public/favicon.ico
  public/logo192.png
  public/logo512.png
  src/App.tsx
  src/components/DaySummary/DaySummary.style.ts
  src/components/DropDownButton/DropDownButton.style.ts
  src/components/DropDownButton/DropDownButton.tsx
  src/components/DropDownButton/type.d.ts
  src/components/HorizontalCard/HorizontalCard.tsx
  src/components/NavBar/NavBar.tsx
  src/components/layout/Layout.style.ts
  src/components/layout/Layout.tsx
  src/pages/MyFavoritePage/MyFavorite.tsx
  src/pages/MyPage/Favorite/MyFavorite.style.ts
  src/pages/MyPage/Favorite/MyFavorite.tsx
  src/pages/MyPage/MyPage.style.ts
  src/pages/MyPage/MyPage.tsx
  src/pages/MyPage/Profile/MyProfile.style.ts
  src/pages/MyPage/Profile/MyProfile.tsx
  src/pages/MyPage/Schedule/DetailSchedule.style.ts
  src/pages/MyPage/Schedule/DetailSchedule.tsx
  src/pages/MyPage/Schedule/MySchedule.style.ts
  src/pages/MyPage/Schedule/MySchedule.tsx
  src/pages/MyPage/SideBar.style.ts
  src/pages/MyPage/SideBar.tsx
  src/pages/MySchedulePage/MySchedule.tsx
  src/pages/ProfilePage/MyProfile.tsx
  src/pages/ReviewDetailPage/ReviewDetailPage.tsx
  src/styles/styles.ts
Labels: :lipstick: DESIGN, :sparkles: FEATURE, :recycle: REFACTOR

#27 [FP-73]feat: miragejs 가입, 로그인, 로그아웃 구현
  package-lock.json
  package.json
  src/components/NavBar/NavBar.tsx
  src/firebase.ts
  src/mirage/index.ts
  src/mirage/routes/authRoutes.ts
  src/pages/LoginPage/SignInForm.tsx
  src/pages/RegisterPage/RegisterForm.tsx
Labels: :sparkles: FEATURE

#29 [FP-20] feat: 카카오맵 API를 연동해서 검색어에 해당하는 리스트 표기
  package-lock.json
  package.json
  public/index.html
  src/components/DropDownButton/DropDownButton.style.ts
  src/components/DropDownButton/DropDownButton.tsx
  src/components/NavBar/NavBar.style.ts
  src/components/NavBar/NavBar.tsx
  src/pages/CreateSchedulePage/AddSchedule.tsx
  src/pages/CreateSchedulePage/CreateScheduleForm.tsx
  src/pages/CreateSchedulePage/SearchBox.tsx
  src/pages/CreateSchedulePage/type.d.ts
  src/pages/MirageExample.tsx
Labels: :bug: BUG, :sparkles: FEATURE
