Repository dogfoot-birdfoot/footprint-front, pull requests merged in 2024-04, with the labels that each got.

#31 refactor: schedule-form boolean에서 accordion으로 전환
  src/pages/CreateSchedulePage/AddDestination.style.ts
  src/pages/CreateSchedulePage/AddDestination.tsx
  src/pages/CreateSchedulePage/AddSchedule.tsx
  src/pages/CreateSchedulePage/CreateScheduleForm.tsx
  src/pages/CreateSchedulePage/LoadSchedule.tsx
Labels: :art: STYLE, :recycle: REFACTOR

#32 refactor: recoil로 상태 이전 및 불필요한 state 제거
  src/components/DropDownButton/DropDownButton.tsx
  src/components/NavBar/NavBar.tsx
  src/components/switch/OnOffSwitch.tsx
  src/components/switch/type.d.ts
  src/hooks/selectedPlaceState.ts
  src/pages/AddReviewPage/AddPost.tsx
  src/pages/CreateSchedulePage/AddDestination.tsx
  src/pages/CreateSchedulePage/AddPost.tsx
  src/pages/CreateSchedulePage/AddSchedule.tsx
  src/pages/CreateSchedulePage/Calendar.tsx
  src/pages/CreateSchedulePage/CreateScheduleForm.tsx
  src/pages/CreateSchedulePage/LoadSchedule.tsx
  src/pages/CreateSchedulePage/SearchBox.tsx
  src/pages/CreateSchedulePage/atom.ts
  src/pages/CreateSchedulePage/type.d.ts
  src/pages/MyPage/Profile/MyProfile.tsx
Labels: :sparkles: FEATURE, :art: STYLE, :recycle: REFACTOR

#34 feat: 리뷰 페이지 기능 추가 및 오류 수정
  src/components/DropDownButton/DropDown.style.ts
  src/components/DropDownButton/DropDownButton.tsx
  src/components/DropDownButton/DropDownCheckBox.tsx
  src/components/DropDownButton/DropDownRadioBox.tsx
  src/components/DropDownButton/type.d.ts
  src/components/ImageSlider/ImageSlider.style.ts
  src/pages/AddReviewPage/AddIntro.tsx
  src/pages/AddReviewPage/AddPictures.tsx
  src/pages/AddReviewPage/AddPost.tsx
Labels: :bug: BUG, :zap: CHORE, :sparkles: FEATURE

#35 feat: 일정 공유 페이지에서 스크롤로 다음 카드 불러오는 기능
  src/components/DropDownButton/DropDownButton.tsx
  src/components/card/CardItem.tsx
  src/pages/ScheduleSharePage/ScheduleSharePage.tsx
  src/pages/ScheduleSharePage/useIntersectionObserver.tsx
Labels: :lipstick: DESIGN, :sparkles: FEATURE, :art: STYLE

#36 Feature : api 연결 진행중
  src/App.tsx
  src/components/NavBar/NavBar.tsx
  src/components/card/CardItem.style.ts
  src/components/card/CardItem.tsx
  src/hooks/atom.ts
  src/hooks/loginAtom.ts
  src/hooks/type.d.ts
  src/mirage/index.ts
  src/mirage/models/user.ts
  src/mirage/routes/authRoutes.ts
  src/mirage/routes/userRoutes.ts
  src/mirage/serializer/user.ts
  src/pages/CreateSchedulePage/AddDestination.tsx
  src/pages/CreateSchedulePage/AddPost.tsx
  src/pages/CreateSchedulePage/AddSchedule.tsx
  src/pages/CreateSchedulePage/Calendar.tsx
  src/pages/CreateSchedulePage/CheckPage.tsx
  src/pages/CreateSchedulePage/LoadSchedule.tsx
  src/pages/CreateSchedulePage/SearchBox.tsx
  src/pages/CreateSchedulePage/type.d.ts
  src/pages/LoginPage/SignInForm.tsx
  src/pages/MirageExample.tsx
  src/pages/RegisterPage/RegisterForm.tsx
  src/pages/RegisterPage/RegisterPage.tsx
  src/pages/ScheduleDetailPage/ScheduleDetailPage.tsx
  src/pages/ScheduleSharePage/ScheduleSharePage.tsx
Labels: :lipstick: DESIGN, :art: STYLE, :recycle: REFACTOR

#37 feat : user id 추가, 정보 조회 api 추가, 상세페이지 api연결
  src/App.tsx
  src/components/DayTab/DayTab.tsx
  src/components/HorizontalCard/HorizontalCard.tsx
  src/components/HorizontalCard/type.d.ts
  src/components/card/CardItem.tsx
  src/mirage/index.ts
  src/pages/CreateSchedulePage/LoadSchedule.tsx
  src/pages/ScheduleDetailPage/ScheduleDetailPage.tsx
  src/pages/ScheduleSharePage/ScheduleSharePage.tsx
  src/pages/UserDetailPage.tsx
Labels: :sparkles: FEATURE

#38 Feat : main page api 연결
  src/components/NavBar/NavBar.style.ts
  src/components/card/CardItem.tsx
  src/index.css
  src/mirage/index.ts
  src/pages/LoginPage/LoginPage.style.ts
  src/pages/MainPage/MainPage.style.ts
  src/pages/MainPage/MainPage.tsx
  src/pages/MainPage/ReviewGallery.style.ts
  src/pages/MainPage/ReviewsGallery.tsx
  src/pages/ScheduleSharePage/ScheduleSharePage.tsx
Labels: :sparkles: FEATURE, :art: STYLE

#39 feat: react-query, devtools 추가 및 mirage server 주석 처리
  package-lock.json
  package.json
  src/App.tsx
  src/components/card/ReviewCardItem.style.ts
  src/components/card/ReviewCardItem.tsx
  src/index.tsx
  src/mirage/index.ts
  src/pages/AddReviewPage/AddPost.tsx
  src/pages/ReviewSharePage/ReviewSharePage.tsx
Labels: :sparkles: FEATURE, :art: STYLE

#40 feat: review api 연결
  src/components/ImageSlider/ImageSlider.tsx
  src/components/ImageSlider/type.d.ts
  src/components/card/ReviewCardItem.tsx
  src/components/card/type.d.ts
  src/pages/AddReviewPage/AddPost.tsx
  src/pages/ReviewSharePage/ReviewSharePage.tsx
  src/pages/ReviewSharePage/useIntersectionObserver.tsx
Labels: :zap: CHORE, :sparkles: FEATURE, :recycle: REFACTOR

#41 Feature: 일정 관련 api 연결
  src/App.tsx
  src/components/HorizontalCard/HorizontalCard.tsx
  src/components/HorizontalCard/type.d.ts
  src/components/card/CardItem.tsx
  src/pages/AddReviewPage/AddPost.tsx
  src/pages/CheckPage/CheckPage.tsx
  src/pages/CreateSchedulePage/AddDestination.tsx
  src/pages/CreateSchedulePage/AddPost.tsx
  src/pages/CreateSchedulePage/AddSchedule.tsx
  src/pages/CreateSchedulePage/CheckPage.tsx
  src/pages/CreateSchedulePage/LoadSchedule.tsx
  src/pages/CreateSchedulePage/type.d.ts
  src/pages/LoadingPage/Loading.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/MainPage/type.d.ts
  src/pages/ReviewSharePage/ReviewSharePage.tsx
  src/pages/ScheduleDetailPage/ScheduleDetailPage.tsx
  src/pages/ScheduleDetailPage/type.d.ts
  src/pages/ScheduleSharePage/ScheduleSharePage.tsx
  src/pages/ScheduleSharePage/type.d.ts
Labels: :sparkles: FEATURE, :ambulance: HOTFIX

#43 Feature: 상세페이지 내부 삭제기능추가
  src/components/HorizontalCard/HorizontalCard.tsx
  src/pages/CreateSchedulePage/AddPost.tsx
  src/pages/CreateSchedulePage/Calendar.tsx
Labels: :sparkles: FEATURE

#42 feat: 무한스크롤로 리뷰 불러오기 및 리뷰 상세페이지 API 연결
  .env
  src/App.tsx
  src/ScrollToTop.ts
  src/components/Buttons/Buttons.tsx
  src/components/HorizontalCard/HorizontalCard.tsx
  src/components/HorizontalCard/type.d.ts
  src/pages/AddReviewPage/AddPictures.tsx
  src/pages/AddReviewPage/AddPost.tsx
  src/pages/AddReviewPage/AddReviewPage.tsx
  src/pages/AddReviewPage/type.d.ts
  src/pages/ReviewDetailPage/ReviewDetailPage.tsx
  src/pages/ReviewSharePage/ReviewSharePage.tsx
  src/pages/ReviewSharePage/type.d.ts
  src/pages/ReviewSharePage/useIntersectionObserver.tsx
Labels: :zap: CHORE, :lipstick: DESIGN, :sparkles: FEATURE, :art: STYLE

#44 feat: 토큰 인증 및 custom hook 추가, kakaoMap 지도 표기 수정
  src/components/NavBar/NavBar.tsx
  src/hooks/type.d.ts
  src/hooks/useCustomFetch.tsx
  src/pages/AddReviewPage/AddPost.tsx
  src/pages/CreateSchedulePage/RouteMap.tsx
  src/pages/LoginPage/SignInForm.tsx
  src/pages/MyPage/Profile/MyProfile.style.ts
  src/pages/MyPage/Schedule/DetailSchedule.style.ts
  src/pages/RegisterPage/RegisterForm.tsx
  src/pages/ReviewDetailPage/ReviewDetailPage.tsx
Labels: :lipstick: DESIGN, :sparkles: FEATURE

#45 [style] 메인 이미지 수정, 로고 수정
  public/favico2n.ico
  public/favicon.ico
  public/footprintlogo2.png
  public/mainImage.jpg
  public/mainImage2.jpg
  public/mainImagePlay.mp4
  public/manifest.json
  src/components/NavBar/NavBar.style.ts
  src/components/NavBar/NavBar.tsx
  src/index.css
  src/pages/CreateSchedulePage/AddPost.tsx
  src/pages/CreateSchedulePage/AddSchedule.tsx
  src/pages/MainPage/MainPage.style.ts
  src/pages/MainPage/MainPage.tsx
Labels: :art: STYLE

#46 Feat : 상세페이지, 지도 api 연결
  public/favicon2.ico
  public/logo2.png
  src/components/DayTab/DayTab.tsx
  src/pages/CreateSchedulePage/AddPost.tsx
  src/pages/CreateSchedulePage/AddSchedule.tsx
  src/pages/CreateSchedulePage/CreateScheduleForm.tsx
  src/pages/CreateSchedulePage/RouteMap.tsx
  src/pages/CreateSchedulePage/SearchBox.tsx
  src/pages/CreateSchedulePage/type.d.ts
  src/pages/ScheduleDetailPage/ScheduleDetailPage.tsx
  src/pages/ScheduleDetailPage/type.d.ts
Labels: :sparkles: FEATURE, :art: STYLE, :ambulance: HOTFIX

#47 feat: 이미지 미리보기, 리뷰 갤러리 API 연결
  package-lock.json
  package.json
  src/App.tsx
  src/components/HorizontalCard/HorizontalCard.tsx
  src/components/ImageSlider/ImageSlider.tsx
  src/components/NavBar/NavBar.tsx
  src/components/card/ReviewCardItem.tsx
  src/components/card/type.d.ts
  src/hooks/atom.ts
  src/hooks/getMemberId.tsx
  src/hooks/type.d.ts
  src/hooks/useCustomFetch.tsx
  src/pages/AddReviewPage/AddPost.tsx
  src/pages/CheckPage/CheckPage.tsx
  src/pages/CreateSchedulePage/AddPost.tsx
  src/pages/LoginPage/LoginPage.style.ts
  src/pages/LoginPage/LoginPage.tsx
  src/pages/LoginPage/SignInForm.tsx
  src/pages/MainPage/ReviewGallery.style.ts
  src/pages/MainPage/ReviewsGallery.tsx
  src/pages/RegisterPage/RegisterForm.tsx
  src/pages/ReviewDetailPage/ReviewDetailPage.tsx
  src/pages/ReviewSharePage/ReviewSharePage.tsx
  src/pages/ReviewSharePage/type.d.ts
  src/pages/ScheduleDetailPage/ScheduleDetailPage.tsx
Labels: :lipstick: DESIGN, :sparkles: FEATURE, :art: STYLE

#48 feat: 일정 보기 무한스크롤 설정, 일정/리뷰 검색 결과
  src/components/DropDownButton/DropDownButton.tsx
  src/components/NavBar/NavBar.tsx
  src/components/NavBar/SearchBar.tsx
  src/components/card/CardItem.tsx
  src/components/layout/Layout.tsx
  src/components/switch/OnOffSwitch.tsx
  src/hooks/useCustomFetch.tsx
  src/pages/CreateSchedulePage/CreateSchedulePage.tsx
  src/pages/ReviewSharePage/ReviewSharePage.tsx
  src/pages/ReviewSharePage/type.d.ts
  src/pages/ScheduleSharePage/ScheduleSharePage.tsx
  src/pages/ScheduleSharePage/useIntersectionObserver.tsx
  src/pages/SearchResultPage/SearchResultPage.tsx
  src/styles/config.ts
Labels: :lipstick: DESIGN, :sparkles: FEATURE

#49 [Feature] 좋아요, 즐겨찾기 api 연결 및 일정 삭제 기능
  src/App.tsx
  src/components/HorizontalCard/HorizontalCard.tsx
  src/components/card/CardItem.tsx
  src/pages/CreateSchedulePage/AddPost.tsx
  src/pages/CreateSchedulePage/AddSchedule.tsx
  src/pages/CreateSchedulePage/type.d.ts
  src/pages/ScheduleDetailPage/ScheduleDetailPage.tsx
  src/pages/ScheduleEditPage/ScheduleEditPage.tsx
  src/pages/ScheduleSharePage/ScheduleSharePage.tsx
Labels: :sparkles: FEATURE, :art: STYLE, :ambulance: HOTFIX

#50 [Chore] 주소수정, 작성일자 임시생성, 메인페이지 정렬 수정
  src/components/HorizontalCard/HorizontalCard.tsx
  src/components/card/CardItem.tsx
  src/pages/MainPage/MainPage.tsx
  src/pages/ScheduleSharePage/ScheduleSharePage.tsx
Labels: :zap: CHORE
